- ec2_vpc_net:
    name: ire.api
    cidr_block: 172.31.0.0/16
    region: "{{ region }}"
    tags:
      Name: ire.api
    state: "{{ state | default('present') }}"
  register: vpc
#- debug: var=vpc
