- name: add keypair
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    name: "{{ key_name }}"
    key_material: "{{ item }}"
  with_file: "file/id_rsa.pub"
