- name: Add DNS name
  route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    overwrite: yes
    zone: bibliman.com
    record: "{{ zone }}.web.bibliman.com"
    type: A
    value: "{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"
