---
- block:
  - name: download apt key
    apt_key:
      id: 0EBFCD88
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  - name: add apt registry
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present
  - name: install docker
    package:
      name: docker-ce,python-pip
      state: latest
  - name: install docker-py
    pip:
      name: docker-py
      state: present
  - name: add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  become: yes
