- name: Gather facts for ire.web instance
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": ire.web
  register: ec2_facts
#- debug: msg={{ ec2_facts.instances }}
- ec2_vpc_net_facts:
    region: "{{ region }}"
    #filters:
      #"tag:Name": ire.web
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: vpc
#- debug: var=vpc
- set_fact: vpc_id={{ vpc.vpcs[0].id }}
- name: add postgres security group
  ec2_group:
    name: "{{ postgres_group }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    description: postgres enabled
    rules:
      - proto: tcp
        ports: 5432
        cidr_ip: "{{ ec2_facts.instances[0].private_ip_address }}/32"
      - proto: tcp
        ports: 5432
        cidr_ip: "{{ ec2_facts.instances[1].private_ip_address }}/32"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
