---
  - block:
    - name: create vpn server config folder
      file: path=/etc/openvpn state=directory
    - name: copy vpn server configs
      copy: src=~/repo/vpn/server/ dest=/etc/openvpn
    - name: install openvpn
      package:
        name: openvpn
        state: latest
    - name: start and enable service
      service: name=openvpn state=restarted enabled=yes
    - name: change config to allow forwarding
      shell: echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    - name: apply config to allow forwarding
      command: sysctl -p
    - name: turn off forwarding
      command: iptables -t nat -D POSTROUTING -o eth0 -s 10.8.0.0/24 -j MASQUERADE
    - name: turn on forwarding
      command: iptables -t nat -I POSTROUTING -o eth0 -s 10.8.0.0/24 -j MASQUERADE
    become: yes
