---
- hosts: local
  tasks:
    - shell: VBoxManage startvm ubuntu1604
      register: result
      ignore_errors: True
    - local_action: wait_for host=dmytro1604.local port=22 search_regex=OpenSSH
      when: result.rc == 0

- hosts: dmytro1604
  remote_user: ubuntu
  tasks:
    - apt: name=update-manager state=absent
      become: yes
#   - apt: upgrade=dist update_cache=yes
#     become: yes
