---
- hosts: volia
  remote_user: ubuntu
  become: yes
  vars:
    service_name: "cjdns"
    source_name: "cjdns-ubuntu2"

  tasks:
    - apt: pkg=nodejs state=latest update_cache=yes cache_valid_time=2500000
    - name: add service
      copy: src=~/repo/{{ source_name }}/contrib/systemd/{{ service_name }}.service dest=/etc/systemd/system
      notify:
        - update service list
    - meta: flush_handlers

    - name: synchronize cjdns sources
      synchronize: src=../../../{{ source_name }}/ dest=~/{{ service_name }} delete=yes
      become: no
    - shell: ./do
      become: no
      args:
        chdir: ~/cjdns
        creates: ~/cjdns/cjdroute
      notify:
        - fetch cjdroute
    - meta: flush_handlers

    - name: add cjdroute to path
      copy: src=~/repo/{{ source_name }}/cjdroute dest=/usr/bin/cjdroute mode="a+x"
    - name: copy cjdroute.conf
      copy: src=~/repo/{{ source_name }}/cjdroute.conf dest=/etc/cjdroute.conf mode=600
    - name: start service
      service: name={{ service_name }} state=restarted enabled=yes

  handlers:
    - name: update service list
      command: systemctl daemon-reload
    - name: fetch cjdroute
      fetch: src=/home/ubuntu/{{ service_name }}/cjdroute dest=~/repo/{{ source_name }}/ flat=yes
