---
- hosts: web
  remote_user: ubuntu
  become: yes
  tasks:
    - apt: pkg=letsencrypt state=latest update_cache=yes
      notify:
        - clean apt lists
    - copy: src=~/repo/letsencrypt dest=/etc follow=yes

  handlers:
    - name: clean apt lists
      file: path='/var/lib/apt/lists/*' state=absent
