- name: Gather facts for ire.web instance
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": ire.web
  register: ec2_facts
#- debug: var=ec2_facts
- rds:
    command: facts
    instance_name: postgres
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: rds_facts
#- debug: var=rds_facts
- set_fact: postgres={{ rds_facts.instance.endpoint }}
#- debug: var=postgres
- name: create web-app folder
  file:
    path: ~/web/target/universal/stage
    state: directory
- name: template production.conf
  template: src=production.conf dest=~/web/production.conf
  notify:
    - restart web.service
  delegate_to: "{{ item.public_ip_address }}"
  delegate_facts: True
  with_items: "{{ ec2_facts.instances }}"
