$vm_gui = false
$vm_memory = 2048
$vm_cpus = 2

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "public_network", ip: "192.168.1.185", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provider :virtualbox do |vb|
    vb.gui = $vm_gui
    vb.memory = $vm_memory
    vb.cpus = $vm_cpus
  end
end
