---
- name: Remove tag
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    resource: "{{ item }}"
    state: absent
    tags:
      Name: ire.api
  with_items: "{{ ec2.instance_ids }}"
