---
- hosts: desk
  become: yes
  tasks:
    - name: download apt key
      apt_key:
        id: 0EBFCD88
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - name: add apt registry
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present
    - name: install docker
      package:
        name: docker-ce,python-pip
        state: latest
    - name: install docker-py
      pip:
        name: docker-py
        state: present
    - name: add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: create a dir for docker ca.crt file
      file:
        path: "/etc/docker/certs.d/puma.rnd.datawerks.de:5000"
        state: directory
        mode: 0750
        recurse: yes
    - name: dance around docker registry
      copy:
        src: "domain.crt"
        dest: "/etc/docker/certs.d/puma.rnd.datawerks.de:5000/ca.crt"
      notify:
        - restart docker
    - meta: flush_handlers

  handlers:
    - name: restart docker
      service: name=docker state=restarted
