- name: Gather facts for ire.api instance
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": ire.api
  register: ec2_facts
- service: name=api state=restarted
  become: yes
  delegate_to: "{{ item.public_ip_address }}"
  with_items: "{{ ec2_facts.instances }}"
