- name: Provision ire.web instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ ami_id }}"
    group: "{{ ssh_play_group }}"
    instance_type: t2.micro
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnets[zone] }}"
    exact_count: "{{ ec2_count }}"
    count_tag:
      Name: ire.web
      Zone: "{{ zone }}"
    instance_tags:
      Name: ire.web
      Zone: "{{ zone }}"
    wait: "{{ wait | default('no') }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2
#- name: Show ec2
  #debug: msg={{ ec2 }}
