- ec2_vpc_net_facts:
    region: "{{ region }}"
    #filters:
      #"tag:Name": ire.web
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: vpc
#- name: Show vpc
  #debug: msg={{ vpc }}
- ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ item.id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  with_items: "{{ vpc.vpcs }}"
  register: subnet
#- name: Show subnet
  #debug: msg={{ subnet.results[0].subnets }}
- name: Provision ire.web instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ ami_id }}"
    group: "{{ ssh_play_group }}"
    instance_type: t2.micro
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnets[availability_zone] }}"
    exact_count: "{{ ec2_count }}"
    count_tag:
      Name: ire.web
      Zone: "{{ availability_zone }}"
    instance_tags:
      Name: ire.web
      Zone: "{{ availability_zone }}"
    wait: "{{ wait | default('no') }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2
#- name: Show ec2
  #debug: msg={{ ec2 }}
