- ec2_vpc_net_facts:
    region: "{{ region }}"
    #filters:
      #"tag:Name": ire.web
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: vpc
#- debug: var=vpc
- set_fact: vpc_id={{ vpc.vpcs[0].id }}
- ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: subnet
#- debug: msg={{ subnet }}
- name: Provision ire.web instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ ami_id }}"
    group: "{{ ssh_play_group }}"
    instance_type: t2.micro
    assign_public_ip: yes
    vpc_subnet_id: "{{ items[0] }}"
    exact_count: "{{ ec2_count }}"
    count_tag:
      Name: ire.web
      Zone: "{{ availability_zone }}"
    instance_tags:
      Name: ire.web
      Zone: "{{ availability_zone }}"
    wait: "{{ wait | default('no') }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  vars:
    subnet_query: "subnets[?availability_zone=='{{ availability_zone }}'].id"
    items: "{{ subnet | json_query(subnet_query) }}"
  register: ec2
#- debug: var=ec2
