- ec2_vpc_net_facts:
    region: "{{ region }}"
    #filters:
      #"tag:Name": ire.web
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: vpc
#- debug: var=vpc
- name: add ssh-play security group
  ec2_group:
    name: "{{ ssh_play_group }}"
    region: "{{ region }}"
    vpc_id: "{{ item.id }}"
    description: ssh, play enabled
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 9000
        cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  with_items: "{{ vpc.vpcs }}"
- name: add web security group
  ec2_group:
    name: web
    region: "{{ region }}"
    vpc_id: "{{ item.id }}"
    description: http port enabled
    rules:
      - proto: tcp
        ports: 80
        cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  with_items: "{{ vpc.vpcs }}"
