- ec2_vpc_net_facts:
    region: "{{ region }}"
    #filters:
      #"tag:Name": ire.api
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: vpc
#- debug: var=vpc
- set_fact: vpc_id={{ vpc.vpcs[0].id }}
- name: add ssh-play security group
  ec2_group:
    name: "{{ ssh_play_group }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    description: ssh, play enabled
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 9000
        cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
- name: add api security group
  ec2_group:
    name: "{{ api_group }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    description: http port enabled
    rules:
      - proto: tcp
        ports: 443
        cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
