---
- block:
  - name: install git,nodejs,gcc,make
    apt:
      name: git,nodejs,gcc,make
      update_cache: yes
      cache_valid_time: 2500000
  - name: download cjdns
    command: git clone https://github.com/cjdelisle/cjdns.git /tmp/cjdns
    args:
      creates: /tmp/cjdns/contrib/systemd/cjdns.service
    become: no
  - shell: ./do
    args:
      chdir: /tmp/cjdns
      creates: /tmp/cjdns/cjdroute
    become: no
  - name: fetch cjdroute
    fetch: src=/tmp/cjdns/cjdroute dest=./ flat=yes
  - name: fetch cjdns.service
    fetch: src=/tmp/cjdns/contrib/upstart/cjdns.conf dest=./ flat=yes
  - name: add cjdroute to path
    copy: src=cjdroute dest=/usr/bin/cjdroute mode="a+x"
  - name: copy cjdroute.conf
    copy: src=~/repo/cjdns/cjdroute.conf-volia dest=/etc/cjdroute.conf mode=600
  - name: add cjdns.conf
    copy: src=cjdns.conf dest=/etc/init/cjdns.conf
  - name: update service list
    command: initctl reload-configuration
  - name: start service
    service: name=cjdns state=restarted enabled=yes
  become: yes
