- name: Add DNS name
  route53:
    state: present
    overwrite: yes
    zone: bibliman.com
    record: "{{ node }}{{ suffix | default('') }}.bibliman.com"
    type: AAAA
    value: "{{ node_ip }}"
    #aws_access_key: "{{ aws_access_key }}"
    #aws_secret_key: "{{ aws_secret_key }}"
