- name: Gather facts for ire.api instance
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": ire.api
  register: ec2_facts
#- debug: var=ec2_facts
- ec2_vpc_net_facts:
    region: "{{ region }}"
    #filters:
      #"tag:Name": ire.api
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: vpc
#- debug: var=vpc
- set_fact: vpc_id={{ vpc.vpcs[0].id }}
- elb_target_group:
    name: tg-api
    region: "{{ region }}"
    protocol: http
    port: 8080
    vpc_id: "{{ vpc_id }}"
    health_check_path: /health
    healthy_threshold_count: 2
    unhealthy_threshold_count: 2
    health_check_timeout: 2
    health_check_interval: 5
    targets: "{{ ec2_facts | json_query('instances[*].{Id: instance_id}') | map('combine', {'Port':8080}) | list }}"
    state: present
    wait_timeout: 240
    wait: True
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
- ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: subnet
#- debug: msg={{ subnet | json_query('subnets[*].id') }}
- elb_application_lb:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: elb-api
    region: "{{ region }}"
    subnets: "{{ subnet | json_query('subnets[*].id') }}"
    security_groups:
      - "{{ api_group }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: tg-api
      - Protocol: HTTPS
        Port: 443
        SslPolicy: ELBSecurityPolicy-2016-08
        Certificates:
          - CertificateArn: "{{ certificate_arn }}"
        DefaultActions:
          - Type: forward
            TargetGroupName: tg-api
    state: present
  register: elb
#- debug: var=elb
