- name: Gather facts for ire.api instance
  ec2_instance_facts:
    #aws_access_key: "{{ aws_access_key }}"
    #aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ ec2_tag }}"
  register: ec2_facts
#- debug: var=ec2_facts
- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip_address }} groups=ec2hosts
  with_items: "{{ ec2_facts.instances }}"
  changed_when: False
