# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook --ask-vault-pass --key-file=~/.ssh/ire/id_rsa --extra-vars="secret=STAGE" aws.yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_count: 1
    wait: yes
  roles:
    - role: keypair
    - role: security-group
    - role: ire-api
      vars:
        availability_zone: "{{ region }}a"
    - role: ire-api-dns
      vars:
        availability_zone: "{{ region }}a"
    - role: ire-api
      vars:
        availability_zone: "{{ region }}b"
    - role: ire-api-dns
      vars:
        availability_zone: "{{ region }}b"
    - role: elb-api
    - role: elb-api-dns
    - role: postgres-security-group
    - role: create-rds
    - role: collect-ec2hosts

- hosts: ec2hosts
  user: ubuntu
  gather_facts: False
  name: PreConfigure ire.api
  roles:
    - role: python-minimal
- hosts: ec2hosts
  user: ubuntu
  name: Configure ire.api
  roles:
    - role: jdk
    - role: ntpd
    - role: docker
    - role: api
- hosts: localhost
  connection: local
  gather_facts: False
  user: ubuntu
  roles:
    - role: production-conf
- hosts: ec2hosts
  user: ubuntu
  roles:
    - role: docker-build
    - role: docker-postgres
