# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook --ask-vault-pass --key-file=~/.ssh/ire/id_rsa --extra-vars="secret=STAGE" aws.yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_count: 1
    wait: yes
  roles:
    - role: keypair
    - role: security-group
    - role: ire-web
      vars:
        availability_zone: "{{ region }}a"
    - role: ire-web-dns
      vars:
        availability_zone: "{{ region }}a"
    - role: ire-web
      vars:
        availability_zone: "{{ region }}b"
    - role: ire-web-dns
      vars:
        availability_zone: "{{ region }}b"
    - role: elb-web
    - role: elb-web-dns
    - role: postgres-security-group
    - role: create-rds

- hosts: ec2hosts
  user: ubuntu
  gather_facts: False
  name: PreConfigure ire.web
  roles:
    - role: python-minimal
- hosts: ec2hosts
  user: ubuntu
  name: Configure ire.web
  roles:
    - role: jdk
    - role: ntpd
    - role: web-app
- hosts: localhost
  connection: local
  gather_facts: False
  user: ubuntu
  roles:
    - role: production-conf
