# ansible-playbook --inventory=inventory/ubuntu init-ubuntu.yaml
---
- hosts: all
  gather_facts: False
  roles:
    - role: python-minimal
- hosts: all
  roles:
    - role: sshd
    - role: jdk
    - role: vim
    #- role: screen
    #- role: disable-dnsmasq
    - role: vm
    - role: docker-ansible
    - role: docker-registry
