# ansible-playbook --inventory=inventory/ubuntu init-ubuntu.yaml
---
- hosts: ubuntu
  gather_facts: False
  roles:
    - role: python-minimal
- hosts: ubuntu
  roles:
    - role: sshd
    - role: jdk
    - role: vim
    - role: screen
    - role: disable-dnsmasq
    - role: vm
    - role: docker-ansible
    - role: docker-registry
