---
- hosts: default
  gather_facts: no
  roles:
    - role: python-minimal
- hosts: default
  become: yes
  tasks:
    - name: install miredo for ipv6
      package:
        name: miredo
        state: present
      become: yes
  roles:
    - cjdns
- hosts: default
  roles:
    - role: external-ipv6
    - role: dns-aaaa
      delegate_to: localhost
      #delegate_facts: True
      vars:
        node_ip: "{{ ipv6.stdout }}"
    - role: ipv6-from-cjdroute-conf
      delegate_to: localhost
    - role: dns-aaaa
      delegate_to: localhost
      vars:
        suffix: ".c"
        node_ip: "{{ cjdns_ipv6.stdout }}"
