# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook --ask-vault-pass remove-aws.yaml
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_count: 0
  roles:
    - role: ire-api
      vars:
        availability_zone: "{{ region }}a"
    - role: tag
      vars:
        a:
    - role: ire-api
      vars:
        availability_zone: "{{ region }}b"
    - role: tag
      vars:
        b:
  tasks:
    - elb_application_lb:
        name: elb-api
        region: "{{ region }}"
        state: absent
        wait: True
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
    - elb_target_group:
        name: tg-api
        region: "{{ region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      retries: 10
