# -*- mode: ruby -*-
# vi: set ft=ruby :

$vm_memory = 2048
$vm_cpus = 2

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  #config.vm.box = "parallels/ubuntu-16.04"

  #config.vm.network "public_network", ip: "192.168.1.185", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provider :virtualbox do |vb|
    vb.memory = $vm_memory
    vb.cpus = $vm_cpus
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "vagrant.yaml"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python2.7"
    }
  end
end
