---
- hosts: default
  gather_facts: no
  become: yes
  tasks:
    - name: Install python 2.7
      raw: apt-get update -qq && apt-get install -qq python-minimal
- hosts: default
  roles:
    - role: jdk
